### PR TITLE
Updating to current master

### PR DESCRIPTION
**Pull request by cafreeman**
Merging current master into sparkr-sql. Getting ready to submit a PR for the data frame stuff so I wanted to clean the diff up before submitting the PR.

### CODE REVIEW

**Comment by shivaram** [comment]
The travis build found an error which we should fix: we need to add `pairRDD.R` to the `Collate` field.

```
'/home/travis/build/amplab-extras/SparkR-pkg/pkg/R' missing from 'Collate' field:
  pairRDD.R
```

**Comment by cafreeman** [comment]
Updated the collate field.

**Comment by shivaram** [comment]
Minor nit -- I think it should be `pairRDD.R` and not `PairRDD.R` (capitalization)

**Comment by cafreeman** [comment]
Sorry, fixed the capitalization.

**Comment by shivaram** [comment]
LGTM -- Thanks @cafreeman . Merging this

**Pull request merged**
