### PR TITLE
Implement string hash code in C.

### PR DESCRIPTION
**Pull request by sun-rui**
[SPARKR-135](https://sparkr.atlassian.net/browse/SPARKR-135). Improve wordcount performance by implement the string hash code in C. The performance improvement is about 10X.
On a 3-worker-node Spark cluster, each node has 16 threads (2.93Ghz Xeon), 48G memory:

3.2 G data  from 96 minutes to 8 minutes
320 M data from 10 minutes to 1 minute

@shivaram I haven't test this patch on Windows, could you help to test it? Thanks.

### CODE REVIEW

**Comment by 7c00** [comment]
This patch works well on my laptop. But when I compiled the pkg, for the first time, on a fresh installed server. An error occurred to me. That is:

> ** testing if installed package can be loaded
Error in dyn.load(file, DLLpath = DLLpath, ...) : 
  unable to load shared object '/home/todd/git/SparkR-pkg/lib/SparkR/libs/SparkR.so':
  /home/todd/git/SparkR-pkg/lib/SparkR/libs/SparkR.so: undefined symbol: IS_SCALAR
Error: loading failed
Execution halted
ERROR: loading failed

The server is running ubuntu 14.04 32bit, with `R version 3.0.2 (2013-09-25)`.

**Comment by shivaram** [comment]
@sun-rui can probably give more details, but I think this is due to the older R version (3.0.2) not having the `IS_SCALAR` symbol. Could you try with a newer version say 3.1.2 ? 

Also we should try to see if we can just symbols present in earlier R versions if this is the problem.

**Comment by 7c00** [comment]
It works after I upgraded R to 3.1.2 !

By the way, is there anything like `make clean`? I had to `rm *.so *.o` by hand now.

**Comment by sun-rui** [comment]
@7c00, you can "cd pkg/src; make clean" 

I was not aware that the IS_SCALAR macro is not supported by earlier versions. But I think this is not an urgent issue to make the code work with those versions. If we receive more user's feedback for using older versions, I can find a portable solution.

**Comment by 7c00** [comment]
@sun-rui Nice! :clap: 

I think it would be better to add some notes or suggestions on R version to README.md before a portable solution comes up.

**Comment by shivaram** [comment]
The `DESCRIPTION` file lists the R version required by a package. Technically we only require R >= 3.0, and I think its good to be backwards compatible with a few R versions. 
One simple fix could be to just import the definition to our file from https://github.com/wch/r-source/blob/70e7151b62fd95ab5660c040073d746073b11032/src/include/Rinternals.h#L319 
Lets open a JIRA to track this.

**Comment by sun-rui** [comment]
Submitted https://sparkr.atlassian.net/browse/SPARKR-166 for this issue.

**Pull request merged**
