### PR TITLE
[SPARKR-224] The serialized flag in a PipelinedRDD is not set correctly.

### PR DESCRIPTION
**Pull request by sun-rui**
This PR fix the issue reported at https://sparkr.atlassian.net/browse/SPARKR-224

### CODE REVIEW

**Comment by shivaram** [comment]
@sun-rui So we actually ran into this problem in the sparkr-sql branch and I refactored the code to introduce a `getSerializedMode` function in https://github.com/amplab-extras/SparkR-pkg/commit/71a73b2561d39df045e7517b675b22ac98079586

Couple of points:
- Can you test to see if that fixes the problem you are seeing ? If it works, can you port the change from sparkr-sql to master ?  
- There are a few other changes which might need to be ported from sparkr-sql to master. It'll be great if we open a JIRA to track this. As a part of that lets also do a merge from master to sparkr-sql to get both branches to a similar state (except for the DataFrame methods which will be in that branch).

**Comment by sun-rui** [comment]
@shivaram, I verified that on the sparkr-sql branch, the bug in unionRDD() is fixed. But I am not sure if it is right to make a backport to master now. As davies submitted a JIRA to merge master into sparkr-sql, should I wait for him to complete it and then start back-porting so that we can reduce duplicate effort?

**Comment by shivaram** [comment]
Hmm sure. I don't mind waiting for one side of the merge to finish before doing the other one. I created https://sparkr.atlassian.net/browse/SPARKR-228 to track this

**Comment by sun-rui** [comment]
Close this PR.

**Pull request closed without merging**
