### PR TITLE
SparkSQL

### PR DESCRIPTION
**Pull request by cafreeman**
This PR incorporates all up-to-date changes in the current amplab master with the additional SparkSQL code generated on my end.  This includes:

- New Java backend
- Build with spark 1.3
- DataFrame API from 1.3
- .Rd files for new functions
- Update NAMESPACE with exports and collate field

@shivaram you may want to update the sparkr-sql branch to mirror the master in order to clean up the diff for this PR.

### CODE REVIEW

**Comment by shivaram** [comment]
@cafreeman I just pushed a merge from `master` to `sparkr-sql`. Can you update the PR ?

**Comment by cafreeman** [comment]
Is there a recommended workflow for this process?  Right now the diff is suddenly showing things involving rJava even though neither of the branches involved in the PR contain them.


On Feb 2, 2015, at 4:19 PM, Shivaram Venkataraman <notifications@github.com<mailto:notifications@github.com>> wrote:


@cafreeman<https://github.com/cafreeman> I just pushed a merge from master to sparkr-sql. Can you update the PR ?

**Comment by shivaram** [comment]
If you only have a few commits (say 5 or 10), I think the cleanest way to do this for now is to clone a new branch that tracks sparkr-sql and then cherry pick the commits that you want into the new  branch. In case you only have new files you can just copy it over or something like that.

In general one good workflow might be for you to create an initial PR that just does a merge from master and then send a PR with your code after that. For example if you did `git merge master` in your client, you could send a PR with just that. Let me know if that makes sense.

**Comment by cafreeman** [comment]
Updated here:

https://github.com/amplab-extras/SparkR-pkg/pull/152

**Pull request closed without merging**
